from util import *

COPY_STRUCTURE = {
	'genfiles': {
		'javascript': Apply(remove_hex_cruft, True),
		'stylesheets': Apply(remove_hex_cruft, True),
		'manifests': Apply(remove_hex_cruft, True),
	},
	'third_party': {
		'javascript-khansrc': [
			'antiscroll',
			'aphrodite',
			'async',
			'babeljs',
			'backbone',
			'balance',
			'birthdaypicker',
			'bootstrap',
			'ckeditor',
			'classnames',
			'console',
			'core',
			'd3',
			'datatables',
			'downloadify',
			'dynatree',
			'es6',
			'fastclick',
			'fetch',
			'flux',
			'Guiders',
			'handlebars',
			'highcharts',
			'icepick',
			'immutable',
			'jquery',
			'jQuery',
			'jqueryui',
			'jsgauge',
			'jszip',
			'kas',
			'katex',
			'live',
			'localeplanet',
			'lodash',
			'mailcheck',
			'masonry',
			'mathquill',
			'method',
			'moment',
			'multimarker',
			'odometer',
			'perseus',
			'placecomplete',
			'qTip2',
			'rainbow',
			'raphael',
			'raven',
			'rcss',
			'react',
			'redux',
			'seedrandom',
			'select2',
			'tota11y',
			'translation',
			'underscore',
			'vivus',
			'xlsx',
		]
	},
	'fonts': True,
	'images': True,
}